# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IwRwUwt0nsxbPrMav-cLST7xDIHKNgOG
"""

import streamlit as st
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from statsmodels.tsa.stattools import coint
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import yfinance as yf
import warnings
import time
import random

warnings.filterwarnings('ignore')

# ---------------------------------------------------------
# 1. 페이지 설정
# ---------------------------------------------------------
st.set_page_config(
    page_title="Pro Quant Dashboard",
    page_icon="⚡",
    layout="wide",
    initial_sidebar_state="expanded"
)

# 커스텀 CSS
st.markdown("""
<style>
    .metric-card {
        background-color: #f0f2f6;
        border-radius: 10px;
        padding: 15px;
        margin: 10px 0;
    }
</style>
""", unsafe_allow_html=True)

st.title("⚡ Pro Quant Pair Trading System")

# ---------------------------------------------------------
# 2. 사이드바 (모드 선택 및 설정)
# ---------------------------------------------------------
with st.sidebar:
    st.header("🎛️ System Control")

    # [핵심] 모드 선택 기능
    app_mode = st.radio("Select Mode", ["📡 Live Analysis (실전)", "🔙 Backtest (과거 검증)"])
    st.divider()

    st.header("⚙️ Strategy Settings")
    window_size = st.slider("Rolling Window (Days)", 20, 120, 60)
    z_threshold = st.slider("Z-Score Threshold", 1.5, 3.0, 2.0, step=0.1)
    p_cutoff = st.slider("Max P-value", 0.01, 0.20, 0.10)

    st.divider()

    # 백테스팅일 때만 날짜 선택창 보여주기
    if app_mode == "🔙 Backtest (과거 검증)":
        st.header("📅 Backtest Period")
        # 기본값: 2023년 1월 ~ 2023년 12월
        col1, col2 = st.columns(2)
        with col1:
            start_date_input = st.date_input("Start Date", datetime(2023, 1, 1))
        with col2:
            end_date_input = st.date_input("End Date", datetime(2023, 12, 31))

        run_label = "RUN BACKTEST 🔙"
    else:
        run_label = "RUN LIVE ANALYSIS 🚀"
        # 라이브 모드는 최근 1년치 데이터 자동 설정
        end_date_input = datetime.now()
        start_date_input = end_date_input - timedelta(days=365)

    run_btn = st.button(run_label, type="primary", use_container_width=True)

# ---------------------------------------------------------
# 3. 데이터 로딩 (날짜 동적 적용)
# ---------------------------------------------------------
@st.cache_data(ttl=3600)
def load_stock_data(start_date, end_date):
    manual_tickers = {
        '005930.KS': '삼성전자', '000660.KS': 'SK하이닉스', '035420.KS': 'NAVER', '035720.KS': '카카오',
        '373220.KS': 'LG에너지솔루션', '006400.KS': '삼성SDI', '051910.KS': 'LG화학', '005490.KS': 'POSCO홀딩스',
        '005380.KS': '현대차', '000270.KS': '기아', '003490.KS': '대한항공', '011200.KS': 'HMM',
        '105560.KS': 'KB금융', '055550.KS': '신한지주', '086790.KS': '하나금융지주', '323410.KS': '카카오뱅크',
        '207940.KS': '삼성바이오로직스', '068270.KS': '셀트리온', '000100.KS': '유한양행', '128940.KS': '한미약품',
        '015760.KS': '한국전력', '033780.KS': 'KT&G', '097950.KS': 'CJ제일제당', '032640.KS': 'LG유플러스',
        '259960.KS': '크래프톤', '009150.KS': '삼성전기', '018260.KS': '삼성SDS', '010130.KS': '고려아연',
        '012330.KS': '현대모비스', '096770.KS': 'SK이노베이션', '011070.KS': 'LG이노텍', '003550.KS': 'LG',
        '032830.KS': '삼성생명', '000810.KS': '삼성화재', '017670.KS': 'SK텔레콤', '030200.KS': 'KT',
        '247540.KQ': '에코프로비엠', '086520.KQ': '에코프로', '196170.KQ': '알테오젠', '028300.KQ': 'HLB'
    }

    # 윈도우 계산을 위해 시작일보다 120일 전 데이터부터 가져옴
    fetch_start = (pd.to_datetime(start_date) - timedelta(days=150)).strftime('%Y-%m-%d')
    fetch_end = pd.to_datetime(end_date).strftime('%Y-%m-%d')

    tickers_list = list(manual_tickers.keys())
    all_data_list = []

    # UI Feedback
    status_text = st.status(f"Fetching data ({fetch_start} ~ {fetch_end})...", expanded=True)

    chunk_size = 5
    for i in range(0, len(tickers_list), chunk_size):
        chunk = tickers_list[i:i + chunk_size]
        try:
            status_text.write(f"📥 Batch {i//chunk_size + 1} Downloading...")
            df_chunk = yf.download(chunk, start=fetch_start, end=fetch_end, progress=False)['Close']

            if isinstance(df_chunk, pd.Series): df_chunk = df_chunk.to_frame(name=chunk[0])
            all_data_list.append(df_chunk)
            time.sleep(random.uniform(0.1, 0.5))
        except: continue

    status_text.update(label="Download Complete!", state="complete", expanded=False)

    if all_data_list:
        df_final = pd.concat(all_data_list, axis=1)
        df_final = df_final.rename(columns=manual_tickers)
        return df_final.ffill().dropna(axis=1)
    return pd.DataFrame()

# ---------------------------------------------------------
# 4. 핵심 엔진 (분석 + 백테스팅)
# ---------------------------------------------------------
def analyze_and_backtest(df_prices, window, threshold, p_cutoff, mode, start_date, end_date):
    pairs = []
    cols = df_prices.columns

    # 분석 기간 설정 (백테스팅이면 지정된 날짜만 잘라서 분석)
    if mode == "🔙 Backtest (과거 검증)":
        mask = (df_prices.index >= pd.to_datetime(start_date)) & (df_prices.index <= pd.to_datetime(end_date))
        df_analysis = df_prices.loc[mask]
    else:
        df_analysis = df_prices # Live는 전체 사용

    if len(df_analysis) < window:
        st.error("데이터 기간이 너무 짧습니다. Rolling Window보다 길어야 합니다.")
        return pd.DataFrame()

    progress_bar = st.progress(0)
    total_checks = len(cols) * (len(cols) - 1) // 2
    checked = 0

    for i in range(len(cols)):
        for j in range(i + 1, len(cols)):
            stock_a = cols[i]
            stock_b = cols[j]

            try:
                # 1. 공적분 검정 (지정된 기간 내에서)
                score, pvalue, _ = coint(df_analysis[stock_a], df_analysis[stock_b])

                if pvalue < p_cutoff:
                    # 2. 지표 계산 (전체 데이터 기준 -> Window 끊김 방지)
                    log_a = np.log(df_prices[stock_a])
                    log_b = np.log(df_prices[stock_b])
                    spread = log_a - log_b

                    rolling_mean = spread.rolling(window=window).mean()
                    rolling_std = spread.rolling(window=window).std()
                    rolling_z = (spread - rolling_mean) / rolling_std

                    # 3. 백테스팅 수익률 계산
                    # (간단한 시뮬레이션: Z < -Thresh Long, Z > Thresh Short)
                    # 전날 시그널 보고 당일 시가 진입 가정 (Shift 1)

                    # 해당 기간의 데이터만 추출
                    z_score_period = rolling_z.loc[df_analysis.index]

                    # 포지션: 1(Long Spread), -1(Short Spread), 0(Neutral)
                    positions = np.where(z_score_period < -threshold, 1,
                                       np.where(z_score_period > threshold, -1, 0))

                    # 각 주식의 수익률
                    ret_a = df_analysis[stock_a].pct_change().fillna(0)
                    ret_b = df_analysis[stock_b].pct_change().fillna(0)

                    # 스프레드 수익률 = (A상승 - B상승) * 포지션
                    # * 포지션은 하루 밀어서 적용 (Look-ahead bias 방지)
                    spread_ret = (ret_a - ret_b) * pd.Series(positions).shift(1).fillna(0).values

                    # 누적 수익률 그래프
                    cum_ret = (1 + spread_ret).cumprod() - 1
                    final_return = cum_ret[-1]

                    # 현재 상태 (Live 모드용)
                    current_z = rolling_z.iloc[-1]
                    corr = df_analysis[stock_a].corr(df_analysis[stock_b])

                    status = "Watch"
                    if current_z < -threshold: status = "Buy A / Sell B"
                    elif current_z > threshold: status = "Sell A / Buy B"

                    pairs.append({
                        'Stock A': stock_a, 'Stock B': stock_b,
                        'Corr': corr, 'P-value': pvalue,
                        'Z-Score': current_z, 'Status': status,
                        'Spread': spread, 'Mean': rolling_mean, 'Std': rolling_std,
                        'Final_Ret': final_return, 'Cum_Ret_Series': cum_ret, # 백테스트용 결과
                        'Analysis_Dates': df_analysis.index
                    })
            except: continue

            checked += 1
            if checked % 10 == 0:
                progress_bar.progress(min(checked / total_checks, 1.0))

    progress_bar.empty()
    return pd.DataFrame(pairs)

# ---------------------------------------------------------
# 5. 차트 그리기 (Live / Backtest 통합)
# ---------------------------------------------------------
def plot_results(row, df_prices, window, threshold, mode):
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, vertical_spacing=0.1,
                        subplot_titles=("Price & Performance", "Rolling Z-Score"),
                        row_heights=[0.6, 0.4])

    sa, sb = row['Stock A'], row['Stock B']

    if mode == "🔙 Backtest (과거 검증)":
        # 백테스트 모드: 누적 수익률 그래프 표시
        dates = row['Analysis_Dates']
        cum_ret = row['Cum_Ret_Series'] * 100 # % 변환
        fig.add_trace(go.Scatter(x=dates, y=cum_ret, name='Strategy Return (%)',
                                 line=dict(color='green', width=2), fill='tozeroy'), row=1, col=1)
        fig.update_yaxes(title_text="Return (%)", row=1, col=1)
    else:
        # 라이브 모드: 정규화 주가 표시
        pa = df_prices[sa]
        pb = df_prices[sb]
        pa_norm = (pa / pa.iloc[0]) * 100
        pb_norm = (pb / pb.iloc[0]) * 100
        fig.add_trace(go.Scatter(x=pa_norm.index, y=pa_norm, name=sa, line=dict(color='#1f77b4')), row=1, col=1)
        fig.add_trace(go.Scatter(x=pb_norm.index, y=pb_norm, name=sb, line=dict(color='#ff7f0e')), row=1, col=1)
        fig.update_yaxes(title_text="Norm Price (100)", row=1, col=1)

    # 하단: Z-Score (공통)
    spread = row['Spread']
    z_score = (spread - row['Mean']) / row['Std']
    # 백테스트면 해당 구간만, 라이브면 전체
    if mode == "🔙 Backtest (과거 검증)":
        z_score = z_score.loc[row['Analysis_Dates']]

    fig.add_trace(go.Scatter(x=z_score.index, y=z_score, name='Z-Score', line=dict(color='#9467bd')), row=2, col=1)
    fig.add_hline(y=threshold, line_dash="dash", line_color="red", row=2, col=1)
    fig.add_hline(y=-threshold, line_dash="dash", line_color="blue", row=2, col=1)
    fig.add_hline(y=0, line_color="black", line_width=0.5, row=2, col=1)

    fig.update_layout(height=500, hovermode="x unified", margin=dict(l=20, r=20, t=30, b=20))
    return fig

# ---------------------------------------------------------
# 6. 메인 실행 블록
# ---------------------------------------------------------
if run_btn:
    # 1. 데이터 로드
    df_prices = load_stock_data(start_date_input, end_date_input)

    if df_prices.empty:
        st.error("데이터 로드 실패. 다시 시도해주세요.")
    else:
        # 2. 분석 실행
        results = analyze_and_backtest(df_prices, window_size, z_threshold, p_cutoff, app_mode, start_date_input, end_date_input)

        if results.empty:
            st.warning("조건을 만족하는 페어를 찾지 못했습니다. (P-value 등을 조절해보세요)")
        else:
            # ------------------------------------------------
            # 모드별 결과 표시
            # ------------------------------------------------
            if app_mode == "🔙 Backtest (과거 검증)":
                st.markdown(f"### 🔙 Backtest Report ({start_date_input} ~ {end_date_input})")

                # 성과 분석
                top_performer = results.loc[results['Final_Ret'].idxmax()]
                avg_return = results['Final_Ret'].mean()

                # KPI
                c1, c2, c3 = st.columns(3)
                c1.metric("Avg Strategy Return", f"{avg_return*100:.2f}%")
                c2.metric("Best Pair Return", f"{top_performer['Final_Ret']*100:.2f}%",
                          f"{top_performer['Stock A']} - {top_performer['Stock B']}")
                c3.metric("Pairs Traded", f"{len(results)}")

                st.divider()

                # 수익률 상위 리스트 탭
                st.subheader("🏆 Top Performing Pairs")

                # 수익률 높은 순 정렬
                sorted_res = results.sort_values(by='Final_Ret', ascending=False)

                for idx, row in sorted_res.head(10).iterrows(): # 상위 10개만
                    with st.expander(f"💰 수익률: {row['Final_Ret']*100:.2f}% | {row['Stock A']} vs {row['Stock B']}", expanded=False):
                        st.plotly_chart(plot_results(row, df_prices, window_size, z_threshold, app_mode), use_container_width=True)

            else:
                # 📡 Live Analysis Mode
                st.markdown("### 📡 Live Signal Dashboard")

                action_items = results[results['Status'] != 'Watch']

                c1, c2, c3 = st.columns(3)
                c1.metric("Pairs Analyzed", f"{len(results)}")
                c2.metric("Active Signals", f"{len(action_items)}", delta="Action Required")

                st.divider()

                tab1, tab2 = st.tabs(["🔥 Signals", "📋 Watchlist"])

                with tab1:
                    if not action_items.empty:
                        for idx, row in action_items.sort_values(by='Z-Score', key=abs, ascending=False).iterrows():
                            status_color = "red" if row['Z-Score'] > 0 else "blue"
                            with st.expander(f":{status_color}[{row['Status']}] {row['Stock A']} vs {row['Stock B']} (Z: {row['Z-Score']:.2f})", expanded=True):
                                st.plotly_chart(plot_results(row, df_prices, window_size, z_threshold, app_mode), use_container_width=True)
                    else:
                        st.info("현재 진입 신호가 발생한 종목이 없습니다.")

                with tab2:
                    st.dataframe(results[['Stock A', 'Stock B', 'Z-Score', 'P-value', 'Corr']].sort_values('P-value'))

else:
    st.info("👈 사이드바에서 모드(Live/Backtest)를 선택하고 실행 버튼을 눌러주세요.")